using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using Mafi;
using Mafi.Core.Factory.Machines;
using Mafi.Core.Ports.Io;
using Mafi.Core.Products;
using Mafi.Core.Prototypes;

namespace CustomAssets.Data.Mod
{
    /// <summary>
    /// Dumps live MachineProto.Ports data to a JSON catalog on disk so external tools
    /// (ModBuilder introspect, per-pack codegen) can read real port names and types
    /// instead of the placeholder catalog shipped in source.
    ///
    /// Invoked from CustomAssetsMod.Initialize once all mods have registered their
    /// prototypes — that's the only point where the ProtosDb is fully populated.
    ///
    /// Output schema matches src/ModBuilder/Data/machine_ports.json exactly so the
    /// two are drop-in compatible. Real port names (single chars like 'A'..'Z')
    /// replace the placeholder 'in1'/'out1' entries.
    /// </summary>
    public static class MachinePortsDumper
    {
        // Cached reflection handle for ProductType.m_protoType (private field carrying
        // the System.Type that classifies the product as Fluid/Loose/Countable/Molten).
        private static readonly FieldInfo s_productTypeProtoTypeField =
            typeof(ProductType).GetField("m_protoType", BindingFlags.NonPublic | BindingFlags.Instance);

        /// <summary>
        /// Write a machine_ports.json catalog under <paramref name="modBasePath"/>/Data/.
        /// Safe to call multiple times — overwrites the file each call.
        /// </summary>
        public static void DumpToJson(ProtosDb db, string modBasePath)
        {
            Log.Info("MachinePortsDumper: starting");
            if (db == null) { Log.Warning("MachinePortsDumper: ProtosDb is null"); return; }
            if (string.IsNullOrEmpty(modBasePath)) { Log.Warning("MachinePortsDumper: modBasePath empty"); return; }

            string dataDir = Path.Combine(modBasePath, "Data");
            try { Directory.CreateDirectory(dataDir); }
            catch (Exception ex) { Log.Warning($"MachinePortsDumper: cannot create '{dataDir}': {ex.Message}"); return; }

            string outFile = Path.Combine(dataDir, "machine_ports.json");
            try
            {
                using (var w = new StreamWriter(outFile, append: false, encoding: Encoding.UTF8))
                {
                    WriteJson(w, db);
                }
                Log.Info($"MachinePortsDumper: wrote {outFile}");
            }
            catch (Exception ex)
            {
                // Surface as ERROR (not Warning) — silent warnings made earlier hangs
                // hard to diagnose. The dumper failing isn't fatal to the game, but it
                // must be visible in the log so we can fix the catalog.
                Log.Error($"MachinePortsDumper: failed to write '{outFile}': {ex.Message}");
                Log.Exception(ex);
            }
        }

        // ---------------------------------------------------------------------
        // JSON writer (hand-rolled — keeps the output deterministic and avoids
        // pulling in a JSON dependency we don't otherwise need at runtime).
        // ---------------------------------------------------------------------

        private static void WriteJson(StreamWriter w, ProtosDb db)
        {
            var machines = db.All<MachineProto>()
                .Where(m => m != null && m.Id != null && m.Id.Value != null)
                .OrderBy(m => m.Id.Value, StringComparer.Ordinal)
                .ToList();

            w.WriteLine("{");
            w.WriteLine("  \"schema\": {");
            w.WriteLine("    \"version\": 2,");
            w.WriteLine("    \"description\": \"Auto-generated by CustomAssets at runtime. Real port names from MachineProto.Ports. Regenerated each game load.\",");
            w.WriteLine("    \"generatedAtUtc\": \"" + DateTime.UtcNow.ToString("o") + "\",");
            w.WriteLine("    \"machineCount\": " + machines.Count);
            w.WriteLine("  },");
            w.WriteLine("  \"machines\": {");

            for (int i = 0; i < machines.Count; i++)
            {
                var m = machines[i];
                WriteMachine(w, m, isLast: i == machines.Count - 1);
            }

            w.WriteLine("  }");
            w.WriteLine("}");
        }

        private static void WriteMachine(StreamWriter w, MachineProto m, bool isLast)
        {
            string id = JsonEscape(m.Id.Value);
            string display = JsonEscape(m.Strings.Name == null ? "" : m.Strings.Name.ToString());

            var inputs = new List<KeyValuePair<string, string>>();
            var outputs = new List<KeyValuePair<string, string>>();
            foreach (var port in m.Ports)
            {
                string name = port.Name.ToString(); // single char in COI
                var shape = port.Shape;
                string productType = shape == null ? "any" : ClassifyProductType(shape.AllowedProductType);
                switch (port.Type)
                {
                    case IoPortType.Input:  inputs.Add(new KeyValuePair<string, string>(name, productType)); break;
                    case IoPortType.Output: outputs.Add(new KeyValuePair<string, string>(name, productType)); break;
                    // IoPortType.Any -> skipped; not currently used by MachineProto.Ports.
                }
            }

            w.WriteLine("    \"" + id + "\": {");
            w.WriteLine("      \"displayName\": \"" + display + "\",");
            w.WriteLine("      \"inputs\": " + WriteNameTypeMap(inputs) + ",");
            w.WriteLine("      \"outputs\": " + WriteNameTypeMap(outputs));
            w.WriteLine("    }" + (isLast ? "" : ","));
        }

        private static string WriteNameTypeMap(List<KeyValuePair<string, string>> ports)
        {
            if (ports.Count == 0) return "{}";
            var sb = new StringBuilder("{");
            for (int i = 0; i < ports.Count; i++)
            {
                if (i > 0) sb.Append(", ");
                sb.Append("\"").Append(JsonEscape(ports[i].Key)).Append("\": \"").Append(ports[i].Value).Append("\"");
            }
            sb.Append("}");
            return sb.ToString();
        }

        // ---------------------------------------------------------------------
        // ProductType -> string category (fluid/unit/loose/molten)
        // ---------------------------------------------------------------------

        private static string ClassifyProductType(ProductType pt)
        {
            if (s_productTypeProtoTypeField == null) return "unknown";
            var protoType = (Type)s_productTypeProtoTypeField.GetValue(pt);
            if (protoType == null) return "any";

            if (typeof(FluidProductProto).IsAssignableFrom(protoType))     return "fluid";
            if (typeof(MoltenProductProto).IsAssignableFrom(protoType))    return "molten";
            if (typeof(LooseProductProto).IsAssignableFrom(protoType))     return "loose";
            if (typeof(CountableProductProto).IsAssignableFrom(protoType)) return "unit";
            return protoType.Name;
        }

        // ---------------------------------------------------------------------
        // Minimal JSON string escaping (avoids pulling in System.Text.Json).
        // ---------------------------------------------------------------------

        private static string JsonEscape(string s)
        {
            if (string.IsNullOrEmpty(s)) return "";
            var sb = new StringBuilder(s.Length);
            foreach (var ch in s)
            {
                switch (ch)
                {
                    case '"':  sb.Append("\\\""); break;
                    case '\\': sb.Append("\\\\"); break;
                    case '\b': sb.Append("\\b"); break;
                    case '\f': sb.Append("\\f"); break;
                    case '\n': sb.Append("\\n"); break;
                    case '\r': sb.Append("\\r"); break;
                    case '\t': sb.Append("\\t"); break;
                    default:
                        if (ch < ' ') sb.AppendFormat("\\u{0:X4}", (int)ch);
                        else sb.Append(ch);
                        break;
                }
            }
            return sb.ToString();
        }
    }
}
