using PythonAPI.Arguments;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using PythonAPI.Runtime;

namespace PythonAPI.Expressions
{
    public class CallExpression : IExpression
    {
        private IExpression expression;
        private List<IArgument> arguments;

        /// Token of the call site (typically the `(` or the callee name) used to
        /// attach file/line context to runtime errors thrown by the callee — most
        /// importantly to argument-validation errors raised by core functions
        /// (AnyArgument.ElseRequiredThrow, NotImplementedException from __call__,
        /// reflection failures, etc.). May be null for synthetic CallExpressions
        /// (e.g. those generated by f-string lowering) that lack a real source.
        private readonly Token callSite;

        public string Path => throw new NotImplementedException($"Cannot get path from operator {GetType()}");

        public IExpression Calle => expression;
        public List<IArgument> Arguments => arguments;

        public CallExpression(IExpression expression, List<IArgument> expressions, Token callSite = null)
        {
            this.expression = expression;
            this.arguments = expressions;
            this.callSite = callSite;
        }

        public Reference<object> GetReference(IDictionary<string, object> context)
        {
            throw new System.NotImplementedException();
        }
		public Task<Reference<object>> GetReferenceAsync(IDictionary<string, object> context) {
			throw new NotImplementedException();
		}

		public object GetValue(IDictionary<string, object> context)
        {
            object executable = expression.GetValue(context);
            if (executable == null) {
                throw wrap(new NullReferenceException($"Null can not be called: {expression}"));
            }

            List<(string name, object value)> arguments = new List<(string name, object value)>();
            foreach (IArgument argument in this.arguments)
            {
                if (argument is NamedArgument named) {
					arguments.Add((named.Name, named.Expression.GetValue(context)));
				} else {
					arguments.Add(((string name, object value))(null, argument.Expression.GetValue(context)));
				}
			}

            try {
                return Expressions.__call__(executable, arguments);
            } catch (PythonParseException) {
                throw;
            } catch (PythonRuntimeException) {
                throw;
            } catch (Exception ex) {
                throw wrap(ex);
            }
        }
		public async Task<object> GetValueAsync(IDictionary<string, object> context) {
			object executable = await expression.GetValueAsync(context);
			if (executable == null) {
				throw wrap(new NullReferenceException($"Null can not be called: {expression}"));
			}

			List<(string name, object value)> arguments = new List<(string name, object value)>();
			foreach (IArgument argument in this.arguments)
			{
				if (argument is NamedArgument named) {
					arguments.Add((named.Name, await named.Expression.GetValueAsync(context)));
				} else {
					arguments.Add(((string name, object value))(null, await argument.Expression.GetValueAsync(context)));
				}
			}

			try {
				return Expressions.__call__async__(executable, arguments);
			} catch (PythonParseException) {
				throw;
			} catch (PythonRuntimeException) {
				throw;
			} catch (Exception ex) {
				throw wrap(ex);
			}
		}

		private Exception wrap(Exception inner) {
			if (callSite is null) {
				return inner;
			}
			return new PythonRuntimeException(callSite.source, callSite.line, callSite.line, inner.Message, inner);
		}
	}
}