<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Configurations>Debug;Release</Configurations>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <WarningLevel>9999</WarningLevel>
    <RunPostBuildEvent>Always</RunPostBuildEvent>
    <Version>0.9.15.5</Version>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>portable</DebugType>
    <DefineConstants>$(DefineConstants);DEV_ONLY</DefineConstants>
    <OutputPath>bin\Debug\</OutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|AnyCPU'">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>portable</DebugType>
    <DefineConstants>$(DefineConstants);DEV_ONLY</DefineConstants>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Data\Tabs\NewIds.Texts.cs" />
    <Content Include="..\ExampleMod.Unity\AssetBundles\**">
        <Link>AssetBundles\%(RecursiveDir)%(Filename)%(Extension)</Link>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Content Remove="..\ExampleMod.Unity\AssetBundles\antenat2_b2ea.manifest" />
    <Content Remove="..\ExampleMod.Unity\AssetBundles\antena_1406.manifest" />
    <Content Remove="..\ExampleMod.Unity\AssetBundles\antena_35ee.manifest" />
    <Content Remove="..\ExampleMod.Unity\AssetBundles\AssetBundles" />
    <Content Remove="..\ExampleMod.Unity\AssetBundles\AssetBundles.manifest" />
    <Content Remove="..\ExampleMod.Unity\AssetBundles\computer_1324.manifest" />
    <Content Remove="..\ExampleMod.Unity\AssetBundles\computer_711d.manifest" />
    <Content Remove="..\ExampleMod.Unity\AssetBundles\display7_200a.manifest" />
    <Content Remove="..\ExampleMod.Unity\AssetBundles\display_c421.manifest" />
    <Content Remove="..\ExampleMod.Unity\AssetBundles\fonts &amp; materials_3fab" />
    <Content Remove="..\ExampleMod.Unity\AssetBundles\fonts &amp; materials_3fab.manifest" />
    <Content Remove="..\ExampleMod.Unity\AssetBundles\fonts &amp; materials_c3ca" />
    <Content Remove="..\ExampleMod.Unity\AssetBundles\fonts &amp; materials_c3ca.manifest" />
    <Content Remove="..\ExampleMod.Unity\AssetBundles\fonts &amp; materials_e750" />
    <Content Remove="..\ExampleMod.Unity\AssetBundles\fonts &amp; materials_e750.manifest" />
    <Content Remove="..\ExampleMod.Unity\AssetBundles\light_75ca.manifest" />
    <Content Remove="..\ExampleMod.Unity\AssetBundles\speaker_9036.manifest" />
    <Content Remove="..\ExampleMod.Unity\AssetBundles\speaker_a04d.manifest" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="mscorlib">
      <HintPath>$(COI_ROOT)\Captain of Industry_Data\Managed\mscorlib.dll</HintPath>
    </Reference>
    <Reference Include="netstandard">
      <HintPath>$(COI_ROOT)\Captain of Industry_Data\Managed\netstandard.dll</HintPath>
    </Reference>
    <Reference Include="System">
      <HintPath>$(COI_ROOT)\Captain of Industry_Data\Managed\System.dll</HintPath>
    </Reference>
    <Reference Include="System.Runtime">
      <HintPath>$(COI_ROOT)\Captain of Industry_Data\Managed\System.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="System.Runtime.Serialization">
      <HintPath>$(COI_ROOT)\Captain of Industry_Data\Managed\System.Runtime.Serialization.dll</HintPath>
    </Reference>
    <Reference Include="System.Security">
      <HintPath>$(COI_ROOT)\Captain of Industry_Data\Managed\System.Security.dll</HintPath>
    </Reference>
    <Reference Include="System.ServiceModel.Internals">
      <HintPath>$(COI_ROOT)\Captain of Industry_Data\Managed\System.ServiceModel.Internals.dll</HintPath>
    </Reference>
    <Reference Include="System.Transactions">
      <HintPath>$(COI_ROOT)\Captain of Industry_Data\Managed\System.Transactions.dll</HintPath>
    </Reference>
    <Reference Include="System.Xml">
      <HintPath>$(COI_ROOT)\Captain of Industry_Data\Managed\System.Xml.dll</HintPath>
    </Reference>
    <Reference Include="System.Xml.Linq">
      <HintPath>$(COI_ROOT)\Captain of Industry_Data\Managed\System.Xml.Linq.dll</HintPath>
    </Reference>
    <Reference Include="System.ComponentModel.Composition">
      <HintPath>$(COI_ROOT)\Captain of Industry_Data\Managed\System.ComponentModel.Composition.dll</HintPath>
    </Reference>
    <Reference Include="System.Configuration">
      <HintPath>$(COI_ROOT)\Captain of Industry_Data\Managed\System.Configuration.dll</HintPath>
    </Reference>
    <Reference Include="System.Core">
      <HintPath>$(COI_ROOT)\Captain of Industry_Data\Managed\System.Core.dll</HintPath>
    </Reference>
    <Reference Include="System.Data.DataSetExtensions">
      <HintPath>$(COI_ROOT)\Captain of Industry_Data\Managed\System.Data.DataSetExtensions.dll</HintPath>
    </Reference>
    <Reference Include="System.Data">
      <HintPath>$(COI_ROOT)\Captain of Industry_Data\Managed\System.Data.dll</HintPath>
    </Reference>
    <Reference Include="System.Drawing">
      <HintPath>$(COI_ROOT)\Captain of Industry_Data\Managed\System.Drawing.dll</HintPath>
    </Reference>
    <Reference Include="System.EnterpriseServices">
      <HintPath>$(COI_ROOT)\Captain of Industry_Data\Managed\System.EnterpriseServices.dll</HintPath>
    </Reference>
    <Reference Include="System.IO.Compression">
      <HintPath>$(COI_ROOT)\Captain of Industry_Data\Managed\System.IO.Compression.dll</HintPath>
    </Reference>	
    <Reference Include="System.IO.Compression.FileSystem">
      <HintPath>$(COI_ROOT)\Captain of Industry_Data\Managed\System.IO.Compression.FileSystem.dll</HintPath>
    </Reference>
    <Reference Include="System.Net.Http">
      <HintPath>$(COI_ROOT)\Captain of Industry_Data\Managed\System.Net.Http.dll</HintPath>
    </Reference>
    <Reference Include="System.Numerics">
      <HintPath>$(COI_ROOT)\Captain of Industry_Data\Managed\System.Numerics.dll</HintPath>
    </Reference>
    <Reference Include="Mafi">
      <HintPath>$(COI_ROOT)\Captain of Industry_Data\Managed\Mafi.dll</HintPath>
    </Reference>
    <Reference Include="Mafi.Core">
      <HintPath>$(COI_ROOT)\Captain of Industry_Data\Managed\Mafi.Core.dll</HintPath>
    </Reference>
    <Reference Include="Mafi.Base">
      <HintPath>$(COI_ROOT)\Captain of Industry_Data\Managed\Mafi.Base.dll</HintPath>
    </Reference>
    <Reference Include="Mafi.Unity">
      <HintPath>$(COI_ROOT)\Captain of Industry_Data\Managed\Mafi.Unity.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AssetBundleModule">
      <HintPath>$(COI_ROOT)\Captain of Industry_Data\Managed\UnityEngine.AssetBundleModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(COI_ROOT)\Captain of Industry_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>$(COI_ROOT)\Captain of Industry_Data\Managed\UnityEngine.InputLegacyModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ParticleSystemModule">
      <HintPath>$(COI_ROOT)\Captain of Industry_Data\Managed\UnityEngine.ParticleSystemModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>$(COI_ROOT)\Captain of Industry_Data\Managed\UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AnimationModule">
      <HintPath>$(COI_ROOT)\Captain of Industry_Data\Managed\UnityEngine.AnimationModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ScreenCaptureModule">
      <HintPath>$(COI_ROOT)\Captain of Industry_Data\Managed\UnityEngine.ScreenCaptureModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>$(COI_ROOT)\Captain of Industry_Data\Managed\UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIModule">
      <HintPath>$(COI_ROOT)\Captain of Industry_Data\Managed\UnityEngine.UIModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TerrainPhysicsModule">
      <HintPath>$(COI_ROOT)\Captain of Industry_Data\Managed\UnityEngine.TerrainPhysicsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UIElementsModule">
      <HintPath>$(COI_ROOT)\Captain of Industry_Data\Managed\UnityEngine.UIElementsModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.VideoModule">
      <HintPath>$(COI_ROOT)\Captain of Industry_Data\Managed\UnityEngine.VideoModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>$(COI_ROOT)\Captain of Industry_Data\Managed\UnityEngine.AudioModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.ImageConversionModule">
      <HintPath>$(COI_ROOT)\Captain of Industry_Data\Managed\UnityEngine.ImageConversionModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.TerrainModule">
      <HintPath>$(COI_ROOT)\Captain of Industry_Data\Managed\UnityEngine.TerrainModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(COI_ROOT)\Captain of Industry_Data\Managed\UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="Unity.VectorGraphics">
      <HintPath>$(COI_ROOT)\Captain of Industry_Data\Managed\Unity.VectorGraphics.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Data\Instructions\Types\" />
    <Folder Include="Translate\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="mkdir &quot;%25APPDATA%25\Captain of Industry\Mods\$(MSBuildProjectName)&quot;" ContinueOnError="true" />
    <Exec Command="copy .\bin\Debug\net48\$(MSBuildProjectName).dll &quot;%25APPDATA%25\Captain of Industry\Mods\$(MSBuildProjectName)&quot;" ContinueOnError="true" />
    <Exec Command="copy .\bin\Debug\net48\$(MSBuildProjectName).pdb &quot;%25APPDATA%25\Captain of Industry\Mods\$(MSBuildProjectName)&quot;" ContinueOnError="true" />
    <Exec Command="robocopy . &quot;%25COI_ROOT%25\Captain of Industry_Data\Managed\$(MSBuildProjectName)&quot; *.cs /S" ContinueOnError="true" />
    <Exec Command="robocopy .\Assets &quot;%25APPDATA%25\Captain of Industry\Mods\$(MSBuildProjectName)\Assets&quot; /S" ContinueOnError="true" />
    <Exec Command="robocopy .\..\ExampleMod.Unity\AssetBundles &quot;%25APPDATA%25\Captain of Industry\Mods\$(MSBuildProjectName)\AssetBundles&quot;" ContinueOnError="true" />
    <Exec Command="robocopy .\..\ProgramableNetwork.Modules\Core &quot;%25APPDATA%25\Captain of Industry\Mods\$(MSBuildProjectName)\Modules\Core&quot;" ContinueOnError="true" />
    <Exec Command="echo &quot;Done&quot;" ContinueOnError="true" />
  </Target>
</Project>
