namespace ProgramableNetwork.Python
{
    public enum PythonTokens
    {
        undefined = 0,
        newline,
        indent,
        dedent,
        lparen,
        rparen,
        llist,
        rlist,
        ldict,
        rdict,
        eq,
        neq,
        lre,
        gre,
        lr,
        gr,
        isp,
        not,
        ink,
        bitand,
        bitor,
        bitxor,
        shiftl,
        shiftr,
        plus,
        minus,
        invert,
        power,
        mul,
        divint,
        div,
        mod,
        dot,
        next,
        set,
        and,
        or,
        str,
        mstr,
        fstrbegin,
        fstrmiddle,
        number,
        none,
        btrue,
        bfalse,
        from,
        import,
        def,
        classp,
        ifp,
        elif,
        elsep,
        block,
        name,
        comment,
        semicolon,
        returnp,
        pass,
        // Loop control — added so PLC scripts can use `for x in xs:`,
        // `while cond:`, plus `break` / `continue` as Python expects.
        // Not used by the bundled Custom/*.py modules (they predate loop
        // support); the lexer dispatches them in Lexer.cs.
        forp,
        whilep,
        breakp,
        continuep,
        eof
    }
}