namespace ProgramableNetwork.Python
{
    public enum PythonTokens
    {
        undefined = 0,
        newline,
        indent,
        dedent,
        lparen,
        rparen,
        llist,
        rlist,
        ldict,
        rdict,
        eq,
        neq,
        lre,
        gre,
        lr,
        gr,
        isp,
        not,
        ink,
        bitand,
        bitor,
        bitxor,
        shiftl,
        shiftr,
        plus,
        minus,
        invert,
        power,
        mul,
        divint,
        div,
        mod,
        dot,
        next,
        set,
        // Augmented assignment operators — `x OP= y` desugars at parse time
        // into `x = x OP y` so the runtime keeps a single AssignmentStatement
        // shape.  Only the six the editor / runtime expose are tokenised;
        // others (`%=`, `**=`, `//=`, `&=`, `|=`, `^=`) would just need new
        // entries here plus matching tokenizer/lexer wiring.
        setplus,
        setminus,
        setmul,
        setdiv,
        setshl,
        setshr,
        and,
        or,
        str,
        mstr,
        fstrbegin,
        fstrmiddle,
        number,
        none,
        btrue,
        bfalse,
        from,
        import,
        def,
        classp,
        ifp,
        elif,
        elsep,
        block,
        name,
        comment,
        semicolon,
        returnp,
        pass,
        // Loop control — added so PLC scripts can use `for x in xs:`,
        // `while cond:`, plus `break` / `continue` as Python expects.
        // Not used by the bundled Custom/*.py modules (they predate loop
        // support); the lexer dispatches them in Lexer.cs.
        forp,
        whilep,
        breakp,
        continuep,
        eof
    }
}