using System.Collections.Generic;
using System.IO;
using System.Text;

namespace CustomAssets.StubBuilder
{
    internal static class StubWriter
    {
        public static void WritePackStub(string outputFile, string modId, ScannedIds ids, ScannedAssets assets, ScannedConfig config)
        {
            var sb = new StringBuilder();
            sb.AppendLine($"# Auto-generated by StubBuilder for mod '{modId}'.");
            sb.AppendLine("# Do not edit by hand.");
            sb.AppendLine();
            sb.AppendLine("from Mafi.Core.Factory.Recipes import RecipeProto");
            sb.AppendLine("from Mafi.Core.Research import ResearchNodeProto");
            sb.AppendLine("from Mafi.Core.Products import ProductProto");
            sb.AppendLine("from Mafi.Core.Factory.Machines import MachineProto");
            sb.AppendLine("from Mafi.Core.Entities.Static.Layout import ToolbarCategoryProto");
            sb.AppendLine();

            WriteIdGroup(sb, "Recipes", ids.Recipes, "RecipeProto.ID");
            WriteIdGroup(sb, "Research", ids.Research, "ResearchNodeProto.ID");
            WriteIdGroup(sb, "Products", ids.Products, "ProductProto.ID");
            WriteIdGroup(sb, "Machines", ids.Machines, "MachineProto.ID");
            WriteIdGroup(sb, "ToolbarCategories", ids.ToolbarCategories, "ToolbarCategoryProto.ID");
            WriteAssetGroup(sb, "Assets", assets.Assets);
            WriteAssetGroup(sb, "AssetBundles", assets.AssetBundles);
            WriteConfigGroup(sb, config);

            Directory.CreateDirectory(Path.GetDirectoryName(outputFile));
            File.WriteAllText(outputFile, sb.ToString());
        }

        private static void WriteIdGroup(StringBuilder sb, string className, SortedSet<string> values, string ctor)
        {
            if (values.Count == 0) return;
            sb.AppendLine($"class {className}:");
            sb.AppendLine("    def __init__(self):");
            sb.AppendLine("        pass");
            foreach (var v in values)
                sb.AppendLine($"    {v} = {ctor}('{v}')");
            sb.AppendLine();
        }

        private static void WriteAssetGroup(StringBuilder sb, string className, SortedDictionary<string, string> entries)
        {
            if (entries.Count == 0) return;
            sb.AppendLine($"class {className}:");
            sb.AppendLine("    def __init__(self):");
            sb.AppendLine("        pass");
            foreach (var kv in entries)
                sb.AppendLine($"    {kv.Key} = '{kv.Value}'");
            sb.AppendLine();
        }

        private static void WriteConfigGroup(StringBuilder sb, ScannedConfig config)
        {
            if (config.IsEmpty) return;
            sb.AppendLine("# config.json fields exposed at runtime as `config.<field>` (see CustomAssets API).");
            sb.AppendLine("# Defaults shown here are the schema defaults; the runtime value may be player-overridden.");
            sb.AppendLine("class Config:");
            sb.AppendLine("    def __init__(self):");
            sb.AppendLine("        pass");
            foreach (var kv in config.Fields)
            {
                if (!string.IsNullOrEmpty(kv.Value.Description))
                    sb.AppendLine($"    # {kv.Value.Description}");
                sb.AppendLine($"    {kv.Key}: {kv.Value.PythonType} = {kv.Value.DefaultRepr}");
            }
            sb.AppendLine();
        }
    }
}
