using System.Collections.Generic;
using System.Globalization;
using System.Text;

namespace CustomAssets.Ui.Primitives {

    /// Plain double-precision 3-vector for procedural primitives. Kept
    /// internal to this folder so it doesn't collide with Mafi's Vec3*.
    public struct V3 {
        public double X;
        public double Y;
        public double Z;
        public V3(double x, double y, double z) { X = x; Y = y; Z = z; }
    }

    public struct V2 {
        public double U;
        public double V;
        public V2(double u, double v) { U = u; V = v; }
    }

    /// One polygon face. Stores per-corner position and UV indices into the
    /// owning <see cref="PrimitiveMesh"/>'s lists (0-based; the OBJ writer
    /// shifts to 1-based on output). Face is open about ngons — quads and
    /// triangles share the same path.
    public sealed class PrimFace {
        public List<int> PositionIdx = new List<int>();
        public List<int> UvIdx = new List<int>();
        /// OBJ group/material name. Optional; used so the modder can later
        /// assign separate materials in Blender (e.g. one for "heap", another
        /// for "container") without re-grouping faces by hand.
        public string GroupName;
    }

    /// Minimal mesh container — positions, UVs, faces. No normals (smoothing
    /// is decided at import time by COI's mesh importer / the user's tool).
    /// Sole writer is <see cref="ToObj"/>; readers don't exist because the
    /// editor never round-trips through this type.
    public sealed class PrimitiveMesh {

        public string Name = "primitive";
        public List<V3> Positions = new List<V3>();
        public List<V2> Uvs = new List<V2>();
        public List<PrimFace> Faces = new List<PrimFace>();

        public int AddVertex(V3 p) {
            Positions.Add(p);
            return Positions.Count - 1;
        }

        public int AddUv(V2 uv) {
            Uvs.Add(uv);
            return Uvs.Count - 1;
        }

        public PrimFace AddFace(int[] posIdx, int[] uvIdx, string group = null) {
            PrimFace f = new PrimFace();
            f.PositionIdx.AddRange(posIdx);
            if (uvIdx != null) f.UvIdx.AddRange(uvIdx);
            f.GroupName = group;
            Faces.Add(f);
            return f;
        }

        /// Wavefront OBJ serialisation. Winding is CCW-from-outside, matching
        /// standard OBJ convention (Blender / Maya / 3ds Max all export CCW).
        /// `ObjLoader.Parse` passes the winding through to Unity unchanged —
        /// Unity's runtime treats CCW as front-facing in practice, so any
        /// reversal anywhere in the load chain ends up with back-facing
        /// triangles. Group lines are emitted only at group boundaries to
        /// keep the file compact.
        public string ToObj() {
            StringBuilder sb = new StringBuilder();
            sb.AppendLine("# Generated by CustomAssets primitive shape generator");
            sb.Append("o ").AppendLine(string.IsNullOrEmpty(Name) ? "mesh" : Name);

            foreach (V3 p in Positions) {
                sb.AppendFormat(CultureInfo.InvariantCulture, "v {0} {1} {2}\n", p.X, p.Y, p.Z);
            }
            foreach (V2 uv in Uvs) {
                sb.AppendFormat(CultureInfo.InvariantCulture, "vt {0} {1}\n", uv.U, uv.V);
            }

            string lastGroup = null;
            foreach (PrimFace f in Faces) {
                if (f.GroupName != lastGroup) {
                    sb.Append("g ").AppendLine(f.GroupName ?? "default");
                    lastGroup = f.GroupName;
                }
                sb.Append('f');
                // Emit corners in author order — CCW from outside, matching
                // standard OBJ convention. ObjLoader.Parse passes the
                // winding through to Unity unchanged; Unity treats CCW as
                // front-facing in practice. Generated .obj files also
                // re-import cleanly into Blender / other DCC tools with no
                // front-face flipping needed.
                for (int i = 0; i < f.PositionIdx.Count; i++) {
                    sb.Append(' ').Append(f.PositionIdx[i] + 1);
                    if (i < f.UvIdx.Count && f.UvIdx[i] >= 0) {
                        sb.Append('/').Append(f.UvIdx[i] + 1);
                    }
                }
                sb.Append('\n');
            }
            return sb.ToString();
        }
    }
}
